export const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function safeUrl(value) { const u = new URL(value, 'https://therwawire.com'); if (u.origin !== 'https://therwawire.com' || u.username || u.password || u.hash || !/^\/(news|learn|rwa|tokenization|institutions)\/[a-z0-9-]+\/$/.test(u.pathname) || u.search) throw new Error('invalid_article_url'); return u.href; }
export function weeklyKey(now = new Date()) {
  const parts = Object.fromEntries(new Intl.DateTimeFormat('en-CA', {timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit',weekday:'short'}).formatToParts(now).map(x=>[x.type,x.value]));
  const days={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6}; const date=new Date(`${parts.year}-${parts.month}-${parts.day}T12:00:00Z`);
  // Friday labels the issue; previews earlier in the week use the upcoming Friday.
  date.setUTCDate(date.getUTCDate() + ((5-days[parts.weekday]+7)%7)); return `weekly-${date.toISOString().slice(0,10)}`;
}
export function selectIssue(feed, now = new Date()) {
  if (!Array.isArray(feed?.articles) || !Number.isFinite(Date.parse(feed.generatedAt)) || Date.parse(feed.generatedAt)>now.valueOf()+60000 || now.valueOf()-Date.parse(feed.generatedAt)>48*3600000) throw new Error('stale_feed');
  const seen=new Set(); const eligible=feed.articles.filter(a=>a.type==='NEWS' && a.category==='news' && !a.draft && Date.parse(a.pubDate)<=now.valueOf() && Date.parse(a.pubDate)>now.valueOf()-7*86400000).sort((a,b)=>Date.parse(b.pubDate)-Date.parse(a.pubDate));
  const stories=[];
  for(const a of eligible) {const url=safeUrl(a.url); if(seen.has(url)) continue; seen.add(url); if(!a.title||!a.description)continue; stories.push({title:String(a.title).slice(0,240),description:String(a.description).slice(0,700),takeaway:String(a.keyTakeaways?.[0]||'').slice(0,500),url,pubDate:new Date(a.pubDate).toISOString()}); if(stories.length===5)break;}
  const guide=feed.articles.filter(a=>a.type==='EXPLAINER'&&a.category==='learn'&&!a.draft&&Date.parse(a.pubDate)<=now.valueOf()).find(a=>a.slug==='what-is-tokenization') ?? feed.articles.find(a=>a.type==='EXPLAINER'&&a.category==='learn'&&!a.draft&&Date.parse(a.pubDate)<=now.valueOf());
  return {id:weeklyKey(now),generatedAt:now.toISOString(),subject:`RWA Wire Weekly — ${weeklyKey(now).slice(7)}`,stories,guide:guide?{title:String(guide.title).slice(0,240),url:safeUrl(guide.url)}:null};
}
export function renderIssue(issue, footer, unsubscribeUrl) {
  if(!issue.stories.length)throw new Error('no_news');
  const name=footer.name||'RWA Wire'; const address=footer.address||'Sender address will be added before sending'; const contact=footer.contact||'';
  const date=new Date(issue.generatedAt).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Berlin'});
  const text=[`RWA WIRE // WEEKLY`,date,'The week in tokenized finance. A short recap of published RWA Wire coverage.',...issue.stories.map((s,i)=>`${i+1}. ${s.title}\n${s.description}\n${s.takeaway ? 'Context: '+s.takeaway+'\n':''}Read the full story: ${safeUrl(s.url)}`),issue.guide?`Back to basics: ${issue.guide.title}\n${safeUrl(issue.guide.url)}`:'',`${name}\n${address}\n${contact}\nYou received this weekly newsletter because you confirmed your subscription.\nUnsubscribe: ${unsubscribeUrl}\nPrivacy: https://therwawire.com/privacy/`].filter(Boolean).join('\n\n');
  const stories=issue.stories.map((s,i)=>`<tr><td style="padding:24px 28px;border-top:1px solid #e5e7eb"><p style="font-size:12px;color:#4b5563">${i+1} // ${esc(new Date(s.pubDate).toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'Europe/Berlin'}))}</p><h2 style="font-size:23px;line-height:1.3;margin:8px 0">${esc(s.title)}</h2><p style="font-size:16px;line-height:1.6">${esc(s.description)}</p>${s.takeaway?`<p style="font-size:15px;line-height:1.6;color:#374151"><strong>Context:</strong> ${esc(s.takeaway)}</p>`:''}<a href="${esc(safeUrl(s.url))}" style="display:inline-block;padding:12px 0;color:#08753e;font-size:16px">Read the full story →</a></td></tr>`).join('');
  const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(issue.subject)}</title></head><body style="margin:0;background:#f3f4f6;color:#111827;font-family:Arial,Helvetica,sans-serif"><div style="display:none;max-height:0;overflow:hidden">${esc(issue.stories[0].title)} — and the week's tokenization coverage.</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:24px 12px"><table role="presentation" cellpadding="0" cellspacing="0" width="600" style="width:100%;max-width:600px;background:#ffffff"><tr><td style="padding:32px 28px;background:#080a0d;color:#ffffff"><p style="color:#65e79d;font-size:13px;letter-spacing:2px">RWA WIRE // WEEKLY</p><h1 style="font-size:32px;line-height:1.2;margin:16px 0">The week in<br>tokenized finance.</h1><p style="font-size:16px;color:#d1d5db;line-height:1.6">${esc(date)} · A short recap of published RWA Wire coverage.</p></td></tr>${stories}${issue.guide?`<tr><td style="padding:24px 28px;background:#effbf4"><h2 style="font-size:22px">Back to basics</h2><a href="${esc(safeUrl(issue.guide.url))}" style="font-size:16px;color:#08753e;display:inline-block;padding:12px 0">${esc(issue.guide.title)} →</a></td></tr>`:''}<tr><td style="padding:28px;font-size:13px;line-height:1.7;color:#4b5563"><strong>${esc(name)}</strong><br>${esc(address)}${contact?`<br>${esc(contact)}`:''}<p>You received this weekly newsletter because you confirmed your subscription.</p><a href="${esc(unsubscribeUrl)}" style="color:#08753e;display:inline-block;padding:12px 0">Unsubscribe</a> · <a href="https://therwawire.com/privacy/" style="color:#08753e">Privacy</a><p>Independent editorial coverage. No investment advice.</p></td></tr></table></td></tr></table></body></html>`;
  return {subject:issue.subject,html,text};
}
export async function hash(value) {return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
export async function unsubscribeToken(secret,email,consentAt) {const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']); return [...new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`unsubscribe:${email}:${consentAt}`)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
