export const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function safeUrl(value) { const u = new URL(value, 'https://therwawire.com'); if (u.origin !== 'https://therwawire.com' || u.username || u.password || u.hash || !/^\/(news|learn|rwa|tokenization|institutions)\/[a-z0-9-]+\/$/.test(u.pathname) || u.search) throw new Error('invalid_article_url'); return u.href; }
export function weeklyKey(now = new Date()) {
  const parts = Object.fromEntries(new Intl.DateTimeFormat('en-CA', {timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit',weekday:'short'}).formatToParts(now).map(x=>[x.type,x.value]));
  const days={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6}; const date=new Date(`${parts.year}-${parts.month}-${parts.day}T12:00:00Z`);
  // Friday labels the issue; previews earlier in the week use the upcoming Friday.
  date.setUTCDate(date.getUTCDate() + ((5-days[parts.weekday]+7)%7)); return `weekly-${date.toISOString().slice(0,10)}`;
}
export function selectIssue(feed, now = new Date()) {
  if (!Array.isArray(feed?.articles) || !Number.isFinite(Date.parse(feed.generatedAt)) || Date.parse(feed.generatedAt)>now.valueOf()+60000 || now.valueOf()-Date.parse(feed.generatedAt)>48*3600000) throw new Error('stale_feed');
  const seen=new Set(); const eligible=feed.articles.filter(a=>a.type==='NEWS' && a.category==='news' && !a.draft && Date.parse(a.pubDate)<=now.valueOf() && Date.parse(a.pubDate)>now.valueOf()-7*86400000).sort((a,b)=>Date.parse(b.pubDate)-Date.parse(a.pubDate));
  const stories=[];
  for(const a of eligible) {const url=safeUrl(a.url); if(seen.has(url)) continue; seen.add(url); if(!a.title||!a.description)continue; stories.push({title:String(a.title).slice(0,240),description:String(a.description).slice(0,700),takeaway:String(a.keyTakeaways?.[0]||'').slice(0,500),url,pubDate:new Date(a.pubDate).toISOString()}); if(stories.length===5)break;}
  const guide=feed.articles.filter(a=>a.type==='EXPLAINER'&&a.category==='learn'&&!a.draft&&Date.parse(a.pubDate)<=now.valueOf()).find(a=>a.slug==='what-is-tokenization') ?? feed.articles.find(a=>a.type==='EXPLAINER'&&a.category==='learn'&&!a.draft&&Date.parse(a.pubDate)<=now.valueOf());
  return {id:weeklyKey(now),generatedAt:now.toISOString(),subject:`RWA Wire Weekly — ${weeklyKey(now).slice(7)}`,stories,guide:guide?{title:String(guide.title).slice(0,240),url:safeUrl(guide.url)}:null};
}
export function renderIssue(issue, footer, unsubscribeUrl) {
  if(!issue.stories.length)throw new Error('no_news');
  const name=footer.name||'RWA Wire'; const address=footer.address||'Sender address will be added before sending'; const contact=footer.contact||'';
  const date=new Date(issue.generatedAt).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Berlin'});
  const text=[`RWA WIRE // WEEKLY`,date,'The week in tokenized finance. A short recap of published RWA Wire coverage.',...issue.stories.map((s,i)=>`${i+1}. ${s.title}\n${s.description}\n${s.takeaway ? 'Context: '+s.takeaway+'\n':''}Read the full story: ${safeUrl(s.url)}`),issue.guide?`Back to basics: ${issue.guide.title}\n${safeUrl(issue.guide.url)}`:'',`${name}\n${address}\n${contact}\nYou received this weekly newsletter because you confirmed your subscription.\nUnsubscribe: ${unsubscribeUrl}\nPrivacy: https://therwawire.com/privacy/`].filter(Boolean).join('\n\n');
  const stories=issue.stories.map((s,i)=>`<tr><td bgcolor="${i===0?'#dceee5':'#edf5f0'}" style="padding:26px 28px;border-top:8px solid #f6f3ec;background:${i===0?'#dceee5':'#edf5f0'}"><p style="margin:0 0 12px;font-size:12px;font-weight:bold;letter-spacing:1px;color:#236449">${i===0?'LEAD STORY':String(i+1).padStart(2,'0')+' // THE WIRE'} · ${esc(new Date(s.pubDate).toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'Europe/Berlin'}))}</p><h2 style="font-family:Georgia,serif;font-size:26px;line-height:1.3;margin:8px 0 16px;color:#102e25">${esc(s.title)}</h2><p style="font-size:16px;line-height:1.65;color:#263c33">${esc(s.description)}</p>${s.takeaway?`<p style="padding:14px 16px;border-left:3px solid #28754f;background:#d6e9df;font-size:15px;line-height:1.6;color:#203a2c"><strong>Why it matters</strong><br>${esc(s.takeaway)}</p>`:''}<a href="${esc(safeUrl(s.url))}" style="display:inline-block;background:#154f38;border:1px solid #154f38;padding:13px 18px;color:#ffffff;font-size:15px;font-weight:bold;text-decoration:none;border-radius:4px">Read story ${i+1} →<span style="font-size:0;line-height:0;"> ${esc(s.title)}</span></a></td></tr>`).join('');
  const html=`<!doctype html><html lang="en" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(issue.subject)}</title></head><body style="margin:0;background:#dce7df;color:#102e25;font-family:Arial,Helvetica,sans-serif"><div lang="en" dir="ltr" style="display:none;max-height:0;overflow:hidden">${esc(issue.stories[0].title)} — and the week's tokenization coverage.</div><table lang="en" dir="ltr" role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:24px 12px"><table role="presentation" cellpadding="0" cellspacing="0" width="600" style="width:100%;max-width:600px;background:#f6f3ec"><tr><td bgcolor="#102e25" style="padding:34px 28px;background:#102e25;color:#ffffff;border-top:6px solid #74e3a6"><p style="margin:0;color:#9cf1be;font-size:14px;font-weight:bold;letter-spacing:2px">RWA WIRE // WEEKLY</p><h1 style="font-family:Georgia,serif;font-size:36px;line-height:1.15;margin:22px 0;color:#ffffff">The week in<br>tokenized finance.</h1><p style="font-size:16px;color:#d1e4d8;line-height:1.6">${esc(date)}<br>Your weekly briefing on the tokenized economy.</p><p style="display:inline-block;margin:10px 0 0;padding:8px 12px;background:#245441;color:#baf3ce;font-size:12px;letter-spacing:1px">${issue.stories.length} STORIES · ONE CLEARER VIEW</p></td></tr>${stories}${issue.guide?`<tr><td bgcolor="#dce9ee" style="padding:26px 28px;border-top:8px solid #f6f3ec;background:#dce9ee"><p style="font-size:12px;font-weight:bold;letter-spacing:1px;color:#294e5a">THE LEARNING DESK</p><h2 style="font-family:Georgia,serif;font-size:26px;margin:10px 0;color:#183844">Back to basics</h2><a href="${esc(safeUrl(issue.guide.url))}" style="font-size:16px;line-height:1.6;font-weight:bold;color:#194c61;display:inline-block;padding:12px 0">${esc(issue.guide.title)} →</a></td></tr>`:''}<tr><td bgcolor="#102e25" style="padding:28px;background:#102e25;font-size:13px;line-height:1.8;color:#d1e4d8"><p style="margin:0 0 12px;font-weight:bold;letter-spacing:1px;color:#9cf1be">${esc(name)}</p>${esc(address)}${contact?`<br>${esc(contact)}`:''}<p>You received this weekly newsletter because you confirmed your subscription.</p><a href="${esc(unsubscribeUrl)}" style="color:#9cf1be;display:inline-block;padding:12px 0">Unsubscribe</a> · <a href="https://therwawire.com/privacy/" style="color:#9cf1be">Privacy</a><p style="margin-bottom:0">Independent editorial coverage. No investment advice.</p></td></tr></table></td></tr></table></body></html>`;
  return {subject:issue.subject,html,text};
}
export async function hash(value) {return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
export async function unsubscribeToken(secret,email,consentAt) {const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']); return [...new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`unsubscribe:${email}:${consentAt}`)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
