#!/usr/bin/env python3
"""Build a validated RWA Wire story package from a reviewed JSON brief."""
import argparse, html, json, pathlib, re
from datetime import date
from urllib.parse import urlparse
ROOT=pathlib.Path(__file__).resolve().parents[1]; ARTICLES=ROOT/"src/content/articles"; IMAGES=ROOT/"public/images/news"; CANDIDATES=ROOT/"publish/candidates"; ALLOWED={"news","rwa","tokenization","institutions","markets","projects","learn"}
def slugify(s):
 s=re.sub(r"[^a-z0-9]+","-",s.lower()).strip("-")
 if not s: raise ValueError("Empty slug")
 return s
def esc_yaml(s): return json.dumps(str(s),ensure_ascii=False)
def mdlink(x): return f'[{x["name"]}]({x["url"]})'
def validate(d):
 for k in ("title","description","why_it_matters","body","sources"):
  if not d.get(k): raise ValueError(f"Missing {k}")
 if not isinstance(d["sources"],list) or not d["sources"]: raise ValueError("sources must be non-empty")
 for s in d["sources"]:
  if not s.get("name") or not s.get("url") or urlparse(s["url"]).scheme!="https": raise ValueError("Every source needs name + HTTPS url")
 if d.get("category","news") not in ALLOWED: raise ValueError("Invalid category")
def deepen(d,body):
 """Add clearly-labelled analysis when an automated source brief is too thin."""
 if len(re.findall(r'\b\w+\b',body))>=230:return body
 hay=(d['title']+' '+d.get('description','')).lower(); category=d.get('category','news')
 if category=='markets':
  context="""## How to read the signal\n\nA single market headline is less useful than the transmission mechanism behind it. RWA Wire therefore watches four follow-through indicators: spot liquidity in Bitcoin and Ethereum, institutional fund flows, derivatives positioning and whether risk appetite spills into tokenized-asset markets. Those indicators help distinguish a short-lived price move from a broader change in market conditions.\n\n## Connection to tokenized finance\n\nTokenized assets do not trade in isolation. Changes in crypto liquidity, funding conditions and institutional positioning can affect demand for onchain collateral, stablecoins and tokenized investment products. The relevant question is not simply whether crypto prices rise or fall, but whether capital is becoming easier or harder to deploy across digital-asset infrastructure."""
 elif 'deposit' in hay or 'settlement' in hay:
  context="""## The infrastructure angle\n\nTokenized deposits matter because the cash leg of an onchain transaction is as important as the asset leg. If regulated bank money can move and settle on compatible rails, institutions can potentially reduce the gap between asset transfer and payment. The practical tests are interoperability, legal finality, operating hours and whether the system works outside a controlled pilot.\n\n## What would make this material\n\nRWA Wire will look for evidence of production use rather than announcements alone: named counterparties, transaction volumes, supported networks, custody arrangements and a clear description of settlement finality. Those details determine whether a tokenized-deposit initiative is infrastructure or still experimentation."""
 elif any(x in hay for x in ['collateral','securit','stock','bond']):
  context="""## The market-structure angle\n\nThe important question is what the tokenized instrument can actually do after issuance. Collateral eligibility, transfer restrictions, custody, redemption and settlement determine whether a digital representation becomes useful financial infrastructure rather than simply a new wrapper around an existing asset.\n\n## What would confirm adoption\n\nWatch for recurring use, additional eligible assets, institutional counterparties and integration with trading or lending workflows. Expansion across those dimensions would be stronger evidence of adoption than token issuance by itself."""
 elif 'fund' in hay or 'treasury' in hay:
  context="""## Why the product structure matters\n\nFor tokenized funds, distribution is only one part of the story. Investors also need clear subscription and redemption mechanics, custody, transfer rules and reliable access to the underlying asset or cash flows. The more of that lifecycle that can operate onchain, the more meaningful the tokenization becomes.\n\n## What would confirm scale\n\nRWA Wire will watch assets under management, supported networks, investor eligibility, secondary transferability and whether the token is accepted elsewhere as collateral or a settlement asset. Those are stronger indicators of utility than launch announcements alone."""
 else:
  context="""## RWA Wire analysis\n\nThe significance of an institutional tokenization announcement depends on what moves from concept to production. The key distinction is between issuing a token and integrating that token into custody, settlement, collateral and investment workflows. RWA Wire tracks those downstream functions because they reveal whether onchain finance is gaining durable utility.\n\n## What would strengthen the signal\n\nThe next evidence to look for is concrete usage: named counterparties, transaction or asset volumes, supported networks, operating jurisdictions and details on custody or settlement. Those data points can turn an announcement into a measurable adoption signal."""
 return body+"\n\n"+context

def svg(title,category):
 c=html.escape(category.upper()); return f'''<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="675" viewBox="0 0 1200 675"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#0D1217"/><stop offset="1" stop-color="#080A0D"/></linearGradient><radialGradient id="r"><stop stop-color="#2ED47A" stop-opacity=".16"/><stop offset="1" stop-color="#2ED47A" stop-opacity="0"/></radialGradient><pattern id="grid" width="48" height="48" patternUnits="userSpaceOnUse"><path d="M48 0H0V48" fill="none" stroke="#1A2229"/></pattern></defs><rect width="1200" height="675" fill="url(#g)"/><rect width="1200" height="675" fill="url(#grid)" opacity=".72"/><circle cx="845" cy="330" r="285" fill="url(#r)"/><rect width="10" height="675" fill="#2ED47A"/><text x="86" y="88" fill="#2ED47A" font-family="Arial" font-size="18" font-weight="700" letter-spacing="4">RWA WIRE // {c}</text><text x="1114" y="88" text-anchor="end" fill="#66717B" font-family="Arial" font-size="14" letter-spacing="3">INTELLIGENCE BRIEF</text><path d="M86 118H1114" stroke="#263038"/><text x="86" y="260" fill="#F5F7FA" font-family="Georgia" font-size="66" font-weight="600">MARKET</text><text x="86" y="330" fill="#F5F7FA" font-family="Georgia" font-size="66" font-weight="600">SIGNAL</text><text x="90" y="382" fill="#8B949E" font-family="Arial" font-size="17" letter-spacing="3">TOKENIZED FINANCE · INSTITUTIONAL FLOW</text><g transform="translate(790 235)"><circle cx="150" cy="100" r="142" fill="none" stroke="#263038" stroke-width="2"/><circle cx="150" cy="100" r="92" fill="none" stroke="#2ED47A" stroke-width="2"/><path d="M8 100h284M150-42v284" stroke="#263038"/><path d="M62 158L116 112l52 18 70-91" fill="none" stroke="#2ED47A" stroke-width="3"/><circle cx="238" cy="39" r="7" fill="#2ED47A"/></g><path d="M86 566H1114" stroke="#263038"/><text x="86" y="610" fill="#8B949E" font-family="Arial" font-size="15" letter-spacing="2">REAL-WORLD ASSETS · TOKENIZATION · INSTITUTIONS · MARKETS</text><text x="1114" y="610" text-anchor="end" fill="#2ED47A" font-family="Arial" font-size="15" font-weight="700">THERWAWIRE.COM</text></svg>'''
def main():
 ap=argparse.ArgumentParser(); ap.add_argument("brief"); a=ap.parse_args(); d=json.loads(pathlib.Path(a.brief).read_text(encoding="utf-8")); validate(d); slug=slugify(d.get("slug") or d["title"]); pub=d.get("pubDate") or date.today().isoformat(); category=d.get("category","news"); article_url=f"https://therwawire.com/{category}/{slug}/"; image_url=f"https://therwawire.com/images/news/{slug}.svg"; tags=d.get("tags") or ["News","RWA","Tokenization"]; take=d.get("keyTakeaways") or [d["why_it_matters"]]; body=deepen(d,d["body"].strip()); sources="\n".join(f"- {mdlink(s)}" for s in d["sources"])
 fm=["---",'type: "NEWS"',f'category: {esc_yaml(category)}',f'title: {esc_yaml(d["title"])}',f'description: {esc_yaml(d["description"])}',f'pubDate: {esc_yaml(pub)}',f'readingTime: {esc_yaml(d.get("readingTime","4 min read"))}',f'heroImage: {esc_yaml("/images/news/"+slug+".svg")}',f'heroImageAlt: {esc_yaml(d.get("heroImageAlt","RWA Wire editorial visual for "+d["title"]))}',"tags: "+json.dumps(tags,ensure_ascii=False),'relatedSlugs: []',"showTradingCTA: false","keyTakeaways:"]+[f"  - {esc_yaml(x)}" for x in take]+["---"]
 article="\n".join(fm)+"\n\n"+body+"\n\n---\n\n**Sources**\n\n"+sources+"\n\n*RWA Wire separates reported facts from its market-context analysis. Source links are provided for verification.*\n"; social=d.get("social") or {}; social_summary=str(social.get("summary") or d["description"]).strip(); hook=social_summary[:220].rstrip()+("…" if len(social_summary)>220 else ""); caption=d.get("caption") or f'RWA WIRE // {d.get("reviewCategory",category).upper()}\n\n{d["title"]}\n\n{hook}\n\nFull analysis →\n{article_url}'; candidate_id=f"{pub}-{slug}"[:55].rstrip("-"); distribution={"telegram":caption,"x":social.get("x") or f'{d["title"]}\n\n{hook}\n\n{article_url}',"breaking":social.get("breaking") or f'RWA WIRE // {d.get("reviewCategory",category).upper()}\n\n{d["title"]}\n\n{article_url}',"summary":social_summary}; candidate={"id":candidate_id,"title":d["title"],"category":d.get("reviewCategory",category).upper(),"why_it_matters":d["why_it_matters"],"article_url":article_url,"image_url":image_url,"caption":caption,"distribution":distribution,"sources":d["sources"]}
 for p in (ARTICLES/f"{slug}.mdx",IMAGES/f"{slug}.svg",CANDIDATES/f'{candidate_id}.json'):
  if p.exists(): raise ValueError(f"Refusing overwrite: {p.relative_to(ROOT)}")
 ARTICLES.mkdir(parents=True,exist_ok=True); IMAGES.mkdir(parents=True,exist_ok=True); CANDIDATES.mkdir(parents=True,exist_ok=True); (ARTICLES/f"{slug}.mdx").write_text(article,encoding="utf-8"); (IMAGES/f"{slug}.svg").write_text(svg(d["title"],d.get("reviewCategory","NEWS")),encoding="utf-8"); cp=CANDIDATES/f'{candidate_id}.json'; cp.write_text(json.dumps(candidate,indent=2,ensure_ascii=False)+"\n",encoding="utf-8"); print(cp.relative_to(ROOT))
if __name__=="__main__": main()
